temperature: 0
top_p: 1
input_path: random_100_datasets_full_metadata.csv
input_format: csv
qrels_input_path: all_research_data_full_metadata.csv
qrels_input_format: csv
output_dir: output/full_metadata_model_comparison
output_dir_by_variant:
  V1_TOPIC_COUNTRY_TIME_ALL_TOPICS: output/full_metadata_model_comparison/v1_all_topics
  V2_TOPIC_COUNTRY_TIME_SINGLE_TOPIC: output/full_metadata_model_comparison/v2_single_topic
  V3_TITLE_ONLY: output/full_metadata_model_comparison/v3_title_only
  V4_TOPIC_COUNTRY_TIME_UNIVERSE_ANALYSIS_UNIT_ALL_TOPICS: output/full_metadata_model_comparison/v4_all_topics_population_unit
  V5_TOPIC_COUNTRY_TIME_UNIVERSE_ALL_TOPICS: output/full_metadata_model_comparison/v5_all_topics_population
  V6_TOPIC_COUNTRY_TIME_ABSTRACT_NATURAL_LANGUAGE: output/full_metadata_model_comparison/v6_all_topics_abstract_natural_language
source_row_limit: 100
sample_per_variant: 0
random_seed: 42
time_format: decade 
query_variants:
  - V1_TOPIC_COUNTRY_TIME_ALL_TOPICS
  #- V2_TOPIC_COUNTRY_TIME_SINGLE_TOPIC
  #- V3_TITLE_ONLY
  #- V4_TOPIC_COUNTRY_TIME_UNIVERSE_ANALYSIS_UNIT_ALL_TOPICS
  #- V5_TOPIC_COUNTRY_TIME_UNIVERSE_ALL_TOPICS
  - V6_TOPIC_COUNTRY_TIME_ABSTRACT_NATURAL_LANGUAGE

modes:
  #- NO_WEB
  - WEB_SEARCH
#model_no_web: gpt-5.1
#model_web: gpt-5.1
models_no_web:
  #- gemma3:27b
  #- gpt-4.1
  #- llama4:latest
  #- gpt-5
  #- gpt-5.1
  #- gpt-5.4
  #- gpt-oss:latest
  #- chat-latest
models_web:
  #- gemma3:27b
  #- gpt-4.1
  #- llama4:latest
  #- gpt-5
  #- gpt-5.1
  #- gpt-5.4
  #- gpt-oss:latest
  - chat-latest
top_k_return: 10
include_top_k_limit_in_prompt: false
max_returned_items_to_save: 0
abstract_query_generator_model: gpt-5.4
abstract_query_generator_api_base_url: https://ai-openwebui.gesis.org/api
abstract_query_generator_api_key_env: OPENWEBUI_API_KEY
abstract_query_cache_file: abstract_query_cache.csv
qrels_strategy: metadata_filter
silver_qrels_fields:
  - abstract
  - content_description
  - categories
  - topics_stw
  - topics_thesoz
  - universe
retrieval_for_candidates: false
retrieval_candidates_k: 30
silver_top_m: 50
#api_base_url: https://ai-openwebui.gesis.org/api
api_key_env: OPENAI_API_KEY #OPENWEBUI_API_KEY
openwebui_web_search_mode: tool_ids
request_timeout_connect_seconds: 30
request_timeout_read_seconds: 600
request_max_retries: 2
request_retry_backoff_seconds: 5
